[alias]
download = "run --quiet --release -- download"
read = "run --quiet --release -- read"
scaffold = "run --quiet --release -- scaffold"
today = "run --quiet --release --features today -- today"

all = "run --quiet --release -- all"
solve = "run --quiet --release -- solve"
time = "run --quiet --release -- time"

[env]
AOC_YEAR = "2025"
